import { Injectable } from '@angular/core';
import { IShopList } from './../models/shop-list.model';

@Injectable({
  providedIn: 'root'
})
export class ShopItemSelectionService {

  public shopList: IShopList[] = [
    {
      shopId: "SUDARSHANNAGARSHOP1",
      shopName: 'Maha Lakshmi Kirana & General Store',
      shopType: "GROCERY",
      shopLocation: "SUDARSHAN NAGAR COLONY",
      shopAddress: "SUDARSHAN NAGAR COLONY",
      shopPostalCode: 500032,
      shopImageUrl: 'https://gravatar.com/avatar/dba6bae8c566f9d4041fb9cd9ada7741?d=identicon&f=y',
      shopRating: 4.5,
      shopOfferedItemsList : [
        {
          itemId: 'MILK1',
          itemName: 'Jersey Milk',
          itemBrand: 'Jersey',
          itemDescription: 'Packaged Milk Tetra Pack',
          itemCategory: 'Packaged',
          itemUndiscountedRate: 10,
          isDiscountedAvailable: false,
          itemDiscountedRate: 10,
          discountAmount: 0,
          discountPercentage: 0,
          itemWeight: 100,
          itemUnit: 'g',
          itemCount: 0,
          itemImageUrl: 'https://gravatar.com/avatar/dba6bae8c566f9d4041fb9cd9ada7741?d=identicon&f=y'
        },
        {
          itemId: 'MILK2',
          itemName: 'Jersey Milk',
          itemBrand: 'Jersey',
          itemDescription: 'Packaged Milk Tetra Pack',
          itemCategory: 'Packaged',
          itemUndiscountedRate: 10,
          isDiscountedAvailable: false,
          itemDiscountedRate: 10,
          discountAmount: 0,
          discountPercentage: 0,
          itemCount: 0,
          itemWeight: 100,
          itemUnit: 'g',
          itemImageUrl: 'https://gravatar.com/avatar/dba6bae8c566f9d4041fb9cd9ada7741?d=identicon&f=y'
        },
        {
          itemId: 'MILK3',
          itemName: 'Jersey Milk',
          itemBrand: 'Jersey',
          itemDescription: 'Packaged Milk Tetra Pack',
          itemCategory: 'Packaged',
          itemUndiscountedRate: 10,
          isDiscountedAvailable: false,
          itemDiscountedRate: 10,
          discountAmount: 0,
          discountPercentage: 0,
          itemCount: 0,
          itemWeight: 100,
          itemUnit: 'g',
          itemImageUrl: 'https://gravatar.com/avatar/dba6bae8c566f9d4041fb9cd9ada7741?d=identicon&f=y'
        },
        {
          itemId: 'MILK4',
          itemName: 'Jersey Milk',
          itemBrand: 'Jersey',
          itemDescription: 'Packaged Milk Tetra Pack',
          itemCategory: 'Packaged',
          itemUndiscountedRate: 10,
          isDiscountedAvailable: false,
          itemDiscountedRate: 10,
          discountAmount: 0,
          discountPercentage: 0,
          itemCount: 0,
          itemWeight: 100,
          itemUnit: 'g',
          itemImageUrl: 'https://gravatar.com/avatar/dba6bae8c566f9d4041fb9cd9ada7741?d=identicon&f=y'
        }
        // {
        //   itemId: 'MILK1',
        //   itemName: 'Jersey Milk',
        //   itemBrand: 'Jersey',
        //   itemDescription: 'Packaged Milk Tetra Pack',
        //   itemCategory: 'Packaged',
        //   itemUndiscountedRate: 10,
        //   isDiscountedAvailable: false,
        //   itemDiscountedRate: 10,
        //   discountAmount: 0,
        //   discountPercentage: 0,
        //   itemWeight: '100 Gms',
        //   itemImageUrl: 'https://gravatar.com/avatar/dba6bae8c566f9d4041fb9cd9ada7741?d=identicon&f=y'
        // },
        // {
        //   itemId: 'MILK1',
        //   itemName: 'Jersey Milk',
        //   itemBrand: 'Jersey',
        //   itemDescription: 'Packaged Milk Tetra Pack',
        //   itemCategory: 'Packaged',
        //   itemUndiscountedRate: 10,
        //   isDiscountedAvailable: false,
        //   itemDiscountedRate: 10,
        //   discountAmount: 0,
        //   discountPercentage: 0,
        //   itemWeight: '100 Gms',
        //   itemImageUrl: 'https://gravatar.com/avatar/dba6bae8c566f9d4041fb9cd9ada7741?d=identicon&f=y'
        // },
        // {
        //   itemId: 'MILK1',
        //   itemName: 'Jersey Milk',
        //   itemBrand: 'Jersey',
        //   itemDescription: 'Packaged Milk Tetra Pack',
        //   itemCategory: 'Packaged',
        //   itemUndiscountedRate: 10,
        //   isDiscountedAvailable: false,
        //   itemDiscountedRate: 10,
        //   discountAmount: 0,
        //   discountPercentage: 0,
        //   itemWeight: '100 Gms',
        //   itemImageUrl: 'https://gravatar.com/avatar/dba6bae8c566f9d4041fb9cd9ada7741?d=identicon&f=y'
        // },
        // {
        //   itemId: 'MILK1',
        //   itemName: 'Jersey Milk',
        //   itemBrand: 'Jersey',
        //   itemDescription: 'Packaged Milk Tetra Pack',
        //   itemCategory: 'Packaged',
        //   itemUndiscountedRate: 10,
        //   isDiscountedAvailable: false,
        //   itemDiscountedRate: 10,
        //   discountAmount: 0,
        //   discountPercentage: 0,
        //   itemWeight: '100 Gms',
        //   itemImageUrl: 'https://gravatar.com/avatar/dba6bae8c566f9d4041fb9cd9ada7741?d=identicon&f=y'
        // },
        // {
        //   itemId: 'MILK1',
        //   itemName: 'Jersey Milk',
        //   itemBrand: 'Jersey',
        //   itemDescription: 'Packaged Milk Tetra Pack',
        //   itemCategory: 'Packaged',
        //   itemUndiscountedRate: 10,
        //   isDiscountedAvailable: false,
        //   itemDiscountedRate: 10,
        //   discountAmount: 0,
        //   discountPercentage: 0,
        //   itemWeight: '100 Gms',
        //   itemImageUrl: 'https://gravatar.com/avatar/dba6bae8c566f9d4041fb9cd9ada7741?d=identicon&f=y'
        // },
        // {
        //   itemId: 'MILK1',
        //   itemName: 'Jersey Milk',
        //   itemBrand: 'Jersey',
        //   itemDescription: 'Packaged Milk Tetra Pack',
        //   itemCategory: 'Packaged',
        //   itemUndiscountedRate: 10,
        //   isDiscountedAvailable: false,
        //   itemDiscountedRate: 10,
        //   discountAmount: 0,
        //   discountPercentage: 0,
        //   itemWeight: '100 Gms',
        //   itemImageUrl: 'https://gravatar.com/avatar/dba6bae8c566f9d4041fb9cd9ada7741?d=identicon&f=y'
        // },
        // {
        //   itemId: 'MILK1',
        //   itemName: 'Jersey Milk',
        //   itemBrand: 'Jersey',
        //   itemDescription: 'Packaged Milk Tetra Pack',
        //   itemCategory: 'Packaged',
        //   itemUndiscountedRate: 10,
        //   isDiscountedAvailable: false,
        //   itemDiscountedRate: 10,
        //   discountAmount: 0,
        //   discountPercentage: 0,
        //   itemWeight: '100 Gms',
        //   itemImageUrl: 'https://gravatar.com/avatar/dba6bae8c566f9d4041fb9cd9ada7741?d=identicon&f=y'
        // },
        // {
        //   itemId: 'MILK1',
        //   itemName: 'Jersey Milk',
        //   itemBrand: 'Jersey',
        //   itemDescription: 'Packaged Milk Tetra Pack',
        //   itemCategory: 'Packaged',
        //   itemUndiscountedRate: 10,
        //   isDiscountedAvailable: false,
        //   itemDiscountedRate: 10,
        //   discountAmount: 0,
        //   discountPercentage: 0,
        //   itemWeight: '100 Gms',
        //   itemImageUrl: 'https://gravatar.com/avatar/dba6bae8c566f9d4041fb9cd9ada7741?d=identicon&f=y'
        // },
        // {
        //   itemId: 'MILK1',
        //   itemName: 'Jersey Milk',
        //   itemBrand: 'Jersey',
        //   itemDescription: 'Packaged Milk Tetra Pack',
        //   itemCategory: 'Packaged',
        //   itemUndiscountedRate: 10,
        //   isDiscountedAvailable: false,
        //   itemDiscountedRate: 10,
        //   discountAmount: 0,
        //   discountPercentage: 0,
        //   itemWeight: '100 Gms',
        //   itemImageUrl: 'https://gravatar.com/avatar/dba6bae8c566f9d4041fb9cd9ada7741?d=identicon&f=y'
        // },
        // {
        //   itemId: 'MILK1',
        //   itemName: 'Jersey Milk',
        //   itemBrand: 'Jersey',
        //   itemDescription: 'Packaged Milk Tetra Pack',
        //   itemCategory: 'Packaged',
        //   itemUndiscountedRate: 10,
        //   isDiscountedAvailable: false,
        //   itemDiscountedRate: 10,
        //   discountAmount: 0,
        //   discountPercentage: 0,
        //   itemWeight: '100 Gms',
        //   itemImageUrl: 'https://gravatar.com/avatar/dba6bae8c566f9d4041fb9cd9ada7741?d=identicon&f=y'
        // },
        // {
        //   itemId: 'MILK1',
        //   itemName: 'Jersey Milk',
        //   itemBrand: 'Jersey',
        //   itemDescription: 'Packaged Milk Tetra Pack',
        //   itemCategory: 'Packaged',
        //   itemUndiscountedRate: 10,
        //   isDiscountedAvailable: false,
        //   itemDiscountedRate: 10,
        //   discountAmount: 0,
        //   discountPercentage: 0,
        //   itemWeight: '100 Gms',
        //   itemImageUrl: 'https://gravatar.com/avatar/dba6bae8c566f9d4041fb9cd9ada7741?d=identicon&f=y'
        // },
        // {
        //   itemId: 'MILK1',
        //   itemName: 'Jersey Milk',
        //   itemBrand: 'Jersey',
        //   itemDescription: 'Packaged Milk Tetra Pack',
        //   itemCategory: 'Packaged',
        //   itemUndiscountedRate: 10,
        //   isDiscountedAvailable: false,
        //   itemDiscountedRate: 10,
        //   discountAmount: 0,
        //   discountPercentage: 0,
        //   itemWeight: '100 Gms',
        //   itemImageUrl: 'https://gravatar.com/avatar/dba6bae8c566f9d4041fb9cd9ada7741?d=identicon&f=y'
        // },
        // {
        //   itemId: 'MILK1',
        //   itemName: 'Jersey Milk',
        //   itemBrand: 'Jersey',
        //   itemDescription: 'Packaged Milk Tetra Pack',
        //   itemCategory: 'Packaged',
        //   itemUndiscountedRate: 10,
        //   isDiscountedAvailable: false,
        //   itemDiscountedRate: 10,
        //   discountAmount: 0,
        //   discountPercentage: 0,
        //   itemWeight: '100 Gms',
        //   itemImageUrl: 'https://gravatar.com/avatar/dba6bae8c566f9d4041fb9cd9ada7741?d=identicon&f=y'
        // },
        // {
        //   itemId: 'MILK1',
        //   itemName: 'Jersey Milk',
        //   itemBrand: 'Jersey',
        //   itemDescription: 'Packaged Milk Tetra Pack',
        //   itemCategory: 'Packaged',
        //   itemUndiscountedRate: 10,
        //   isDiscountedAvailable: false,
        //   itemDiscountedRate: 10,
        //   discountAmount: 0,
        //   discountPercentage: 0,
        //   itemWeight: '100 Gms',
        //   itemImageUrl: 'https://gravatar.com/avatar/dba6bae8c566f9d4041fb9cd9ada7741?d=identicon&f=y'
        // },
        // {
        //   itemId: 'MILK1',
        //   itemName: 'Jersey Milk',
        //   itemBrand: 'Jersey',
        //   itemDescription: 'Packaged Milk Tetra Pack',
        //   itemCategory: 'Packaged',
        //   itemUndiscountedRate: 10,
        //   isDiscountedAvailable: false,
        //   itemDiscountedRate: 10,
        //   discountAmount: 0,
        //   discountPercentage: 0,
        //   itemWeight: '100 Gms',
        //   itemImageUrl: 'https://gravatar.com/avatar/dba6bae8c566f9d4041fb9cd9ada7741?d=identicon&f=y'
        // },
        // {
        //   itemId: 'MILK1',
        //   itemName: 'Jersey Milk',
        //   itemBrand: 'Jersey',
        //   itemDescription: 'Packaged Milk Tetra Pack',
        //   itemCategory: 'Packaged',
        //   itemUndiscountedRate: 10,
        //   isDiscountedAvailable: false,
        //   itemDiscountedRate: 10,
        //   discountAmount: 0,
        //   discountPercentage: 0,
        //   itemWeight: '100 Gms',
        //   itemImageUrl: 'https://gravatar.com/avatar/dba6bae8c566f9d4041fb9cd9ada7741?d=identicon&f=y'
        // },
        // {
        //   itemId: 'MILK1',
        //   itemName: 'Jersey Milk',
        //   itemBrand: 'Jersey',
        //   itemDescription: 'Packaged Milk Tetra Pack',
        //   itemCategory: 'Packaged',
        //   itemUndiscountedRate: 10,
        //   isDiscountedAvailable: false,
        //   itemDiscountedRate: 10,
        //   discountAmount: 0,
        //   discountPercentage: 0,
        //   itemWeight: '100 Gms',
        //   itemImageUrl: 'https://gravatar.com/avatar/dba6bae8c566f9d4041fb9cd9ada7741?d=identicon&f=y'
        // },
        // {
        //   itemId: 'MILK1',
        //   itemName: 'Jersey Milk',
        //   itemBrand: 'Jersey',
        //   itemDescription: 'Packaged Milk Tetra Pack',
        //   itemCategory: 'Packaged',
        //   itemUndiscountedRate: 10,
        //   isDiscountedAvailable: false,
        //   itemDiscountedRate: 10,
        //   discountAmount: 0,
        //   discountPercentage: 0,
        //   itemWeight: '100 Gms',
        //   itemImageUrl: 'https://gravatar.com/avatar/dba6bae8c566f9d4041fb9cd9ada7741?d=identicon&f=y'
        // },
        // {
        //   itemId: 'MILK1',
        //   itemName: 'Jersey Milk',
        //   itemBrand: 'Jersey',
        //   itemDescription: 'Packaged Milk Tetra Pack',
        //   itemCategory: 'Packaged',
        //   itemUndiscountedRate: 10,
        //   isDiscountedAvailable: false,
        //   itemDiscountedRate: 10,
        //   discountAmount: 0,
        //   discountPercentage: 0,
        //   itemWeight: '100 Gms',
        //   itemImageUrl: 'https://gravatar.com/avatar/dba6bae8c566f9d4041fb9cd9ada7741?d=identicon&f=y'
        // },
        // {
        //   itemId: 'MILK1',
        //   itemName: 'Jersey Milk',
        //   itemBrand: 'Jersey',
        //   itemDescription: 'Packaged Milk Tetra Pack',
        //   itemCategory: 'Packaged',
        //   itemUndiscountedRate: 10,
        //   isDiscountedAvailable: false,
        //   itemDiscountedRate: 10,
        //   discountAmount: 0,
        //   discountPercentage: 0,
        //   itemWeight: '100 Gms',
        //   itemImageUrl: 'https://gravatar.com/avatar/dba6bae8c566f9d4041fb9cd9ada7741?d=identicon&f=y'
        // },
        // {
        //   itemId: 'MILK1',
        //   itemName: 'Jersey Milk',
        //   itemBrand: 'Jersey',
        //   itemDescription: 'Packaged Milk Tetra Pack',
        //   itemCategory: 'Packaged',
        //   itemUndiscountedRate: 10,
        //   isDiscountedAvailable: false,
        //   itemDiscountedRate: 10,
        //   discountAmount: 0,
        //   discountPercentage: 0,
        //   itemWeight: '100 Gms',
        //   itemImageUrl: 'https://gravatar.com/avatar/dba6bae8c566f9d4041fb9cd9ada7741?d=identicon&f=y'
        // },
        // {
        //   itemId: 'MILK1',
        //   itemName: 'Jersey Milk',
        //   itemBrand: 'Jersey',
        //   itemDescription: 'Packaged Milk Tetra Pack',
        //   itemCategory: 'Packaged',
        //   itemUndiscountedRate: 10,
        //   isDiscountedAvailable: false,
        //   itemDiscountedRate: 10,
        //   discountAmount: 0,
        //   discountPercentage: 0,
        //   itemWeight: '100 Gms',
        //   itemImageUrl: 'https://gravatar.com/avatar/dba6bae8c566f9d4041fb9cd9ada7741?d=identicon&f=y'
        // },
        // {
        //   itemId: 'MILK1',
        //   itemName: 'Jersey Milk',
        //   itemBrand: 'Jersey',
        //   itemDescription: 'Packaged Milk Tetra Pack',
        //   itemCategory: 'Packaged',
        //   itemUndiscountedRate: 10,
        //   isDiscountedAvailable: false,
        //   itemDiscountedRate: 10,
        //   discountAmount: 0,
        //   discountPercentage: 0,
        //   itemWeight: '100 Gms',
        //   itemImageUrl: 'https://gravatar.com/avatar/dba6bae8c566f9d4041fb9cd9ada7741?d=identicon&f=y'
        // },
        // {
        //   itemId: 'MILK1',
        //   itemName: 'Jersey Milk',
        //   itemBrand: 'Jersey',
        //   itemDescription: 'Packaged Milk Tetra Pack',
        //   itemCategory: 'Packaged',
        //   itemUndiscountedRate: 10,
        //   isDiscountedAvailable: false,
        //   itemDiscountedRate: 10,
        //   discountAmount: 0,
        //   discountPercentage: 0,
        //   itemWeight: '100 Gms',
        //   itemImageUrl: 'https://gravatar.com/avatar/dba6bae8c566f9d4041fb9cd9ada7741?d=identicon&f=y'
        // },
        // {
        //   itemId: 'MILK1',
        //   itemName: 'Jersey Milk',
        //   itemBrand: 'Jersey',
        //   itemDescription: 'Packaged Milk Tetra Pack',
        //   itemCategory: 'Packaged',
        //   itemUndiscountedRate: 10,
        //   isDiscountedAvailable: false,
        //   itemDiscountedRate: 10,
        //   discountAmount: 0,
        //   discountPercentage: 0,
        //   itemWeight: '100 Gms',
        //   itemImageUrl: 'https://gravatar.com/avatar/dba6bae8c566f9d4041fb9cd9ada7741?d=identicon&f=y'
        // },
        // {
        //   itemId: 'MILK1',
        //   itemName: 'Jersey Milk',
        //   itemBrand: 'Jersey',
        //   itemDescription: 'Packaged Milk Tetra Pack',
        //   itemCategory: 'Packaged',
        //   itemUndiscountedRate: 10,
        //   isDiscountedAvailable: false,
        //   itemDiscountedRate: 10,
        //   discountAmount: 0,
        //   discountPercentage: 0,
        //   itemWeight: '100 Gms',
        //   itemImageUrl: 'https://gravatar.com/avatar/dba6bae8c566f9d4041fb9cd9ada7741?d=identicon&f=y'
        // },
        // {
        //   itemId: 'MILK1',
        //   itemName: 'Jersey Milk',
        //   itemBrand: 'Jersey',
        //   itemDescription: 'Packaged Milk Tetra Pack',
        //   itemCategory: 'Packaged',
        //   itemUndiscountedRate: 10,
        //   isDiscountedAvailable: false,
        //   itemDiscountedRate: 10,
        //   discountAmount: 0,
        //   discountPercentage: 0,
        //   itemWeight: '100 Gms',
        //   itemImageUrl: 'https://gravatar.com/avatar/dba6bae8c566f9d4041fb9cd9ada7741?d=identicon&f=y'
        // },
        // {
        //   itemId: 'MILK1',
        //   itemName: 'Jersey Milk',
        //   itemBrand: 'Jersey',
        //   itemDescription: 'Packaged Milk Tetra Pack',
        //   itemCategory: 'Packaged',
        //   itemUndiscountedRate: 10,
        //   isDiscountedAvailable: false,
        //   itemDiscountedRate: 10,
        //   discountAmount: 0,
        //   discountPercentage: 0,
        //   itemWeight: '100 Gms',
        //   itemImageUrl: 'https://gravatar.com/avatar/dba6bae8c566f9d4041fb9cd9ada7741?d=identicon&f=y'
        // },
        // {
        //   itemId: 'MILK1',
        //   itemName: 'Jersey Milk',
        //   itemBrand: 'Jersey',
        //   itemDescription: 'Packaged Milk Tetra Pack',
        //   itemCategory: 'Packaged',
        //   itemUndiscountedRate: 10,
        //   isDiscountedAvailable: false,
        //   itemDiscountedRate: 10,
        //   discountAmount: 0,
        //   discountPercentage: 0,
        //   itemWeight: '100 Gms',
        //   itemImageUrl: 'https://gravatar.com/avatar/dba6bae8c566f9d4041fb9cd9ada7741?d=identicon&f=y'
        // },
        // {
        //   itemId: 'MILK1',
        //   itemName: 'Jersey Milk',
        //   itemBrand: 'Jersey',
        //   itemDescription: 'Packaged Milk Tetra Pack',
        //   itemCategory: 'Packaged',
        //   itemUndiscountedRate: 10,
        //   isDiscountedAvailable: false,
        //   itemDiscountedRate: 10,
        //   discountAmount: 0,
        //   discountPercentage: 0,
        //   itemWeight: '100 Gms',
        //   itemImageUrl: 'https://gravatar.com/avatar/dba6bae8c566f9d4041fb9cd9ada7741?d=identicon&f=y'
        // },
        // {
        //   itemId: 'MILK1',
        //   itemName: 'Jersey Milk',
        //   itemBrand: 'Jersey',
        //   itemDescription: 'Packaged Milk Tetra Pack',
        //   itemCategory: 'Packaged',
        //   itemUndiscountedRate: 10,
        //   isDiscountedAvailable: false,
        //   itemDiscountedRate: 10,
        //   discountAmount: 0,
        //   discountPercentage: 0,
        //   itemWeight: '100 Gms',
        //   itemImageUrl: 'https://gravatar.com/avatar/dba6bae8c566f9d4041fb9cd9ada7741?d=identicon&f=y'
        // },
        // {
        //   itemId: 'MILK1',
        //   itemName: 'Jersey Milk',
        //   itemBrand: 'Jersey',
        //   itemDescription: 'Packaged Milk Tetra Pack',
        //   itemCategory: 'Packaged',
        //   itemUndiscountedRate: 10,
        //   isDiscountedAvailable: false,
        //   itemDiscountedRate: 10,
        //   discountAmount: 0,
        //   discountPercentage: 0,
        //   itemWeight: '100 Gms',
        //   itemImageUrl: 'https://gravatar.com/avatar/dba6bae8c566f9d4041fb9cd9ada7741?d=identicon&f=y'
        // },
        // {
        //   itemId: 'MILK1',
        //   itemName: 'Jersey Milk',
        //   itemBrand: 'Jersey',
        //   itemDescription: 'Packaged Milk Tetra Pack',
        //   itemCategory: 'Packaged',
        //   itemUndiscountedRate: 10,
        //   isDiscountedAvailable: false,
        //   itemDiscountedRate: 10,
        //   discountAmount: 0,
        //   discountPercentage: 0,
        //   itemWeight: '100 Gms',
        //   itemImageUrl: 'https://gravatar.com/avatar/dba6bae8c566f9d4041fb9cd9ada7741?d=identicon&f=y'
        // },
        // {
        //   itemId: 'MILK1',
        //   itemName: 'Jersey Milk',
        //   itemBrand: 'Jersey',
        //   itemDescription: 'Packaged Milk Tetra Pack',
        //   itemCategory: 'Packaged',
        //   itemUndiscountedRate: 10,
        //   isDiscountedAvailable: false,
        //   itemDiscountedRate: 10,
        //   discountAmount: 0,
        //   discountPercentage: 0,
        //   itemWeight: '100 Gms',
        //   itemImageUrl: 'https://gravatar.com/avatar/dba6bae8c566f9d4041fb9cd9ada7741?d=identicon&f=y'
        // },
        // {
        //   itemId: 'MILK1',
        //   itemName: 'Jersey Milk',
        //   itemBrand: 'Jersey',
        //   itemDescription: 'Packaged Milk Tetra Pack',
        //   itemCategory: 'Packaged',
        //   itemUndiscountedRate: 10,
        //   isDiscountedAvailable: false,
        //   itemDiscountedRate: 10,
        //   discountAmount: 0,
        //   discountPercentage: 0,
        //   itemWeight: '100 Gms',
        //   itemImageUrl: 'https://gravatar.com/avatar/dba6bae8c566f9d4041fb9cd9ada7741?d=identicon&f=y'
        // },
        // {
        //   itemId: 'MILK1',
        //   itemName: 'Jersey Milk',
        //   itemBrand: 'Jersey',
        //   itemDescription: 'Packaged Milk Tetra Pack',
        //   itemCategory: 'Packaged',
        //   itemUndiscountedRate: 10,
        //   isDiscountedAvailable: false,
        //   itemDiscountedRate: 10,
        //   discountAmount: 0,
        //   discountPercentage: 0,
        //   itemWeight: '100 Gms',
        //   itemImageUrl: 'https://gravatar.com/avatar/dba6bae8c566f9d4041fb9cd9ada7741?d=identicon&f=y'
        // },
        // {
        //   itemId: 'MILK1',
        //   itemName: 'Jersey Milk',
        //   itemBrand: 'Jersey',
        //   itemDescription: 'Packaged Milk Tetra Pack',
        //   itemCategory: 'Packaged',
        //   itemUndiscountedRate: 10,
        //   isDiscountedAvailable: false,
        //   itemDiscountedRate: 10,
        //   discountAmount: 0,
        //   discountPercentage: 0,
        //   itemWeight: '100 Gms',
        //   itemImageUrl: 'https://gravatar.com/avatar/dba6bae8c566f9d4041fb9cd9ada7741?d=identicon&f=y'
        // },
        // {
        //   itemId: 'MILK1',
        //   itemName: 'Jersey Milk',
        //   itemBrand: 'Jersey',
        //   itemDescription: 'Packaged Milk Tetra Pack',
        //   itemCategory: 'Packaged',
        //   itemUndiscountedRate: 10,
        //   isDiscountedAvailable: false,
        //   itemDiscountedRate: 10,
        //   discountAmount: 0,
        //   discountPercentage: 0,
        //   itemWeight: '100 Gms',
        //   itemImageUrl: 'https://gravatar.com/avatar/dba6bae8c566f9d4041fb9cd9ada7741?d=identicon&f=y'
        // },
        // {
        //   itemId: 'MILK1',
        //   itemName: 'Jersey Milk',
        //   itemBrand: 'Jersey',
        //   itemDescription: 'Packaged Milk Tetra Pack',
        //   itemCategory: 'Packaged',
        //   itemUndiscountedRate: 10,
        //   isDiscountedAvailable: false,
        //   itemDiscountedRate: 10,
        //   discountAmount: 0,
        //   discountPercentage: 0,
        //   itemWeight: '100 Gms',
        //   itemImageUrl: 'https://gravatar.com/avatar/dba6bae8c566f9d4041fb9cd9ada7741?d=identicon&f=y'
        // },
        // {
        //   itemId: 'MILK1',
        //   itemName: 'Jersey Milk',
        //   itemBrand: 'Jersey',
        //   itemDescription: 'Packaged Milk Tetra Pack',
        //   itemCategory: 'Packaged',
        //   itemUndiscountedRate: 10,
        //   isDiscountedAvailable: false,
        //   itemDiscountedRate: 10,
        //   discountAmount: 0,
        //   discountPercentage: 0,
        //   itemWeight: '100 Gms',
        //   itemImageUrl: 'https://gravatar.com/avatar/dba6bae8c566f9d4041fb9cd9ada7741?d=identicon&f=y'
        // },
        // {
        //   itemId: 'MILK1',
        //   itemName: 'Jersey Milk',
        //   itemBrand: 'Jersey',
        //   itemDescription: 'Packaged Milk Tetra Pack',
        //   itemCategory: 'Packaged',
        //   itemUndiscountedRate: 10,
        //   isDiscountedAvailable: false,
        //   itemDiscountedRate: 10,
        //   discountAmount: 0,
        //   discountPercentage: 0,
        //   itemWeight: '100 Gms',
        //   itemImageUrl: 'https://gravatar.com/avatar/dba6bae8c566f9d4041fb9cd9ada7741?d=identicon&f=y'
        // },
        // {
        //   itemId: 'MILK1',
        //   itemName: 'Jersey Milk',
        //   itemBrand: 'Jersey',
        //   itemDescription: 'Packaged Milk Tetra Pack',
        //   itemCategory: 'Packaged',
        //   itemUndiscountedRate: 10,
        //   isDiscountedAvailable: false,
        //   itemDiscountedRate: 10,
        //   discountAmount: 0,
        //   discountPercentage: 0,
        //   itemWeight: '100 Gms',
        //   itemImageUrl: 'https://gravatar.com/avatar/dba6bae8c566f9d4041fb9cd9ada7741?d=identicon&f=y'
        // },
        // {
        //   itemId: 'MILK1',
        //   itemName: 'Jersey Milk',
        //   itemBrand: 'Jersey',
        //   itemDescription: 'Packaged Milk Tetra Pack',
        //   itemCategory: 'Packaged',
        //   itemUndiscountedRate: 10,
        //   isDiscountedAvailable: false,
        //   itemDiscountedRate: 10,
        //   discountAmount: 0,
        //   discountPercentage: 0,
        //   itemWeight: '100 Gms',
        //   itemImageUrl: 'https://gravatar.com/avatar/dba6bae8c566f9d4041fb9cd9ada7741?d=identicon&f=y'
        // },
        // {
        //   itemId: 'MILK1',
        //   itemName: 'Jersey Milk',
        //   itemBrand: 'Jersey',
        //   itemDescription: 'Packaged Milk Tetra Pack',
        //   itemCategory: 'Packaged',
        //   itemUndiscountedRate: 10,
        //   isDiscountedAvailable: false,
        //   itemDiscountedRate: 10,
        //   discountAmount: 0,
        //   discountPercentage: 0,
        //   itemWeight: '100 Gms',
        //   itemImageUrl: 'https://gravatar.com/avatar/dba6bae8c566f9d4041fb9cd9ada7741?d=identicon&f=y'
        // },
        // {
        //   itemId: 'MILK1',
        //   itemName: 'Jersey Milk',
        //   itemBrand: 'Jersey',
        //   itemDescription: 'Packaged Milk Tetra Pack',
        //   itemCategory: 'Packaged',
        //   itemUndiscountedRate: 10,
        //   isDiscountedAvailable: false,
        //   itemDiscountedRate: 10,
        //   discountAmount: 0,
        //   discountPercentage: 0,
        //   itemWeight: '100 Gms',
        //   itemImageUrl: 'https://gravatar.com/avatar/dba6bae8c566f9d4041fb9cd9ada7741?d=identicon&f=y'
        // },
        // {
        //   itemId: 'MILK1',
        //   itemName: 'Jersey Milk',
        //   itemBrand: 'Jersey',
        //   itemDescription: 'Packaged Milk Tetra Pack',
        //   itemCategory: 'Packaged',
        //   itemUndiscountedRate: 10,
        //   isDiscountedAvailable: false,
        //   itemDiscountedRate: 10,
        //   discountAmount: 0,
        //   discountPercentage: 0,
        //   itemWeight: '100 Gms',
        //   itemImageUrl: 'https://gravatar.com/avatar/dba6bae8c566f9d4041fb9cd9ada7741?d=identicon&f=y'
        // },
        // {
        //   itemId: 'MILK1',
        //   itemName: 'Jersey Milk',
        //   itemBrand: 'Jersey',
        //   itemDescription: 'Packaged Milk Tetra Pack',
        //   itemCategory: 'Packaged',
        //   itemUndiscountedRate: 10,
        //   isDiscountedAvailable: false,
        //   itemDiscountedRate: 10,
        //   discountAmount: 0,
        //   discountPercentage: 0,
        //   itemWeight: '100 Gms',
        //   itemImageUrl: 'https://gravatar.com/avatar/dba6bae8c566f9d4041fb9cd9ada7741?d=identicon&f=y'
        // },
        // {
        //   itemId: 'MILK1',
        //   itemName: 'Jersey Milk',
        //   itemBrand: 'Jersey',
        //   itemDescription: 'Packaged Milk Tetra Pack',
        //   itemCategory: 'Packaged',
        //   itemUndiscountedRate: 10,
        //   isDiscountedAvailable: false,
        //   itemDiscountedRate: 10,
        //   discountAmount: 0,
        //   discountPercentage: 0,
        //   itemWeight: '100 Gms',
        //   itemImageUrl: 'https://gravatar.com/avatar/dba6bae8c566f9d4041fb9cd9ada7741?d=identicon&f=y'
        // },
        // {
        //   itemId: 'MILK1',
        //   itemName: 'Jersey Milk',
        //   itemBrand: 'Jersey',
        //   itemDescription: 'Packaged Milk Tetra Pack',
        //   itemCategory: 'Packaged',
        //   itemUndiscountedRate: 10,
        //   isDiscountedAvailable: false,
        //   itemDiscountedRate: 10,
        //   discountAmount: 0,
        //   discountPercentage: 0,
        //   itemWeight: '100 Gms',
        //   itemImageUrl: 'https://gravatar.com/avatar/dba6bae8c566f9d4041fb9cd9ada7741?d=identicon&f=y'
        // },
        // {
        //   itemId: 'MILK1',
        //   itemName: 'Jersey Milk',
        //   itemBrand: 'Jersey',
        //   itemDescription: 'Packaged Milk Tetra Pack',
        //   itemCategory: 'Packaged',
        //   itemUndiscountedRate: 10,
        //   isDiscountedAvailable: false,
        //   itemDiscountedRate: 10,
        //   discountAmount: 0,
        //   discountPercentage: 0,
        //   itemWeight: '100 Gms',
        //   itemImageUrl: 'https://gravatar.com/avatar/dba6bae8c566f9d4041fb9cd9ada7741?d=identicon&f=y'
        // },
        // {
        //   itemId: 'MILK1',
        //   itemName: 'Jersey Milk',
        //   itemBrand: 'Jersey',
        //   itemDescription: 'Packaged Milk Tetra Pack',
        //   itemCategory: 'Packaged',
        //   itemUndiscountedRate: 10,
        //   isDiscountedAvailable: false,
        //   itemDiscountedRate: 10,
        //   discountAmount: 0,
        //   discountPercentage: 0,
        //   itemWeight: '100 Gms',
        //   itemImageUrl: 'https://gravatar.com/avatar/dba6bae8c566f9d4041fb9cd9ada7741?d=identicon&f=y'
        // },
        // {
        //   itemId: 'MILK1',
        //   itemName: 'Jersey Milk',
        //   itemBrand: 'Jersey',
        //   itemDescription: 'Packaged Milk Tetra Pack',
        //   itemCategory: 'Packaged',
        //   itemUndiscountedRate: 10,
        //   isDiscountedAvailable: false,
        //   itemDiscountedRate: 10,
        //   discountAmount: 0,
        //   discountPercentage: 0,
        //   itemWeight: '100 Gms',
        //   itemImageUrl: 'https://gravatar.com/avatar/dba6bae8c566f9d4041fb9cd9ada7741?d=identicon&f=y'
        // },
        // {
        //   itemId: 'MILK1',
        //   itemName: 'Jersey Milk',
        //   itemBrand: 'Jersey',
        //   itemDescription: 'Packaged Milk Tetra Pack',
        //   itemCategory: 'Packaged',
        //   itemUndiscountedRate: 10,
        //   isDiscountedAvailable: false,
        //   itemDiscountedRate: 10,
        //   discountAmount: 0,
        //   discountPercentage: 0,
        //   itemWeight: '100 Gms',
        //   itemImageUrl: 'https://gravatar.com/avatar/dba6bae8c566f9d4041fb9cd9ada7741?d=identicon&f=y'
        // },
        // {
        //   itemId: 'MILK1',
        //   itemName: 'Jersey Milk',
        //   itemBrand: 'Jersey',
        //   itemDescription: 'Packaged Milk Tetra Pack',
        //   itemCategory: 'Packaged',
        //   itemUndiscountedRate: 10,
        //   isDiscountedAvailable: false,
        //   itemDiscountedRate: 10,
        //   discountAmount: 0,
        //   discountPercentage: 0,
        //   itemWeight: '100 Gms',
        //   itemImageUrl: 'https://gravatar.com/avatar/dba6bae8c566f9d4041fb9cd9ada7741?d=identicon&f=y'
        // },
        // {
        //   itemId: 'MILK1',
        //   itemName: 'Jersey Milk',
        //   itemBrand: 'Jersey',
        //   itemDescription: 'Packaged Milk Tetra Pack',
        //   itemCategory: 'Packaged',
        //   itemUndiscountedRate: 10,
        //   isDiscountedAvailable: false,
        //   itemDiscountedRate: 10,
        //   discountAmount: 0,
        //   discountPercentage: 0,
        //   itemWeight: '100 Gms',
        //   itemImageUrl: 'https://gravatar.com/avatar/dba6bae8c566f9d4041fb9cd9ada7741?d=identicon&f=y'
        // },
        // {
        //   itemId: 'MILK1',
        //   itemName: 'Jersey Milk',
        //   itemBrand: 'Jersey',
        //   itemDescription: 'Packaged Milk Tetra Pack',
        //   itemCategory: 'Packaged',
        //   itemUndiscountedRate: 10,
        //   isDiscountedAvailable: false,
        //   itemDiscountedRate: 10,
        //   discountAmount: 0,
        //   discountPercentage: 0,
        //   itemWeight: '100 Gms',
        //   itemImageUrl: 'https://gravatar.com/avatar/dba6bae8c566f9d4041fb9cd9ada7741?d=identicon&f=y'
        // },
        // {
        //   itemId: 'MILK1',
        //   itemName: 'Jersey Milk',
        //   itemBrand: 'Jersey',
        //   itemDescription: 'Packaged Milk Tetra Pack',
        //   itemCategory: 'Packaged',
        //   itemUndiscountedRate: 10,
        //   isDiscountedAvailable: false,
        //   itemDiscountedRate: 10,
        //   discountAmount: 0,
        //   discountPercentage: 0,
        //   itemWeight: '100 Gms',
        //   itemImageUrl: 'https://gravatar.com/avatar/dba6bae8c566f9d4041fb9cd9ada7741?d=identicon&f=y'
        // },
        // {
        //   itemId: 'MILK1',
        //   itemName: 'Jersey Milk',
        //   itemBrand: 'Jersey',
        //   itemDescription: 'Packaged Milk Tetra Pack',
        //   itemCategory: 'Packaged',
        //   itemUndiscountedRate: 10,
        //   isDiscountedAvailable: false,
        //   itemDiscountedRate: 10,
        //   discountAmount: 0,
        //   discountPercentage: 0,
        //   itemWeight: '100 Gms',
        //   itemImageUrl: 'https://gravatar.com/avatar/dba6bae8c566f9d4041fb9cd9ada7741?d=identicon&f=y'
        // },
        // {
        //   itemId: 'MILK1',
        //   itemName: 'Jersey Milk',
        //   itemBrand: 'Jersey',
        //   itemDescription: 'Packaged Milk Tetra Pack',
        //   itemCategory: 'Packaged',
        //   itemUndiscountedRate: 10,
        //   isDiscountedAvailable: false,
        //   itemDiscountedRate: 10,
        //   discountAmount: 0,
        //   discountPercentage: 0,
        //   itemWeight: '100 Gms',
        //   itemImageUrl: 'https://gravatar.com/avatar/dba6bae8c566f9d4041fb9cd9ada7741?d=identicon&f=y'
        // },
        // {
        //   itemId: 'MILK1',
        //   itemName: 'Jersey Milk',
        //   itemBrand: 'Jersey',
        //   itemDescription: 'Packaged Milk Tetra Pack',
        //   itemCategory: 'Packaged',
        //   itemUndiscountedRate: 10,
        //   isDiscountedAvailable: false,
        //   itemDiscountedRate: 10,
        //   discountAmount: 0,
        //   discountPercentage: 0,
        //   itemWeight: '100 Gms',
        //   itemImageUrl: 'https://gravatar.com/avatar/dba6bae8c566f9d4041fb9cd9ada7741?d=identicon&f=y'
        // },
        // {
        //   itemId: 'MILK1',
        //   itemName: 'Jersey Milk',
        //   itemBrand: 'Jersey',
        //   itemDescription: 'Packaged Milk Tetra Pack',
        //   itemCategory: 'Packaged',
        //   itemUndiscountedRate: 10,
        //   isDiscountedAvailable: false,
        //   itemDiscountedRate: 10,
        //   discountAmount: 0,
        //   discountPercentage: 0,
        //   itemWeight: '100 Gms',
        //   itemImageUrl: 'https://gravatar.com/avatar/dba6bae8c566f9d4041fb9cd9ada7741?d=identicon&f=y'
        // },
        // {
        //   itemId: 'MILK1',
        //   itemName: 'Jersey Milk',
        //   itemBrand: 'Jersey',
        //   itemDescription: 'Packaged Milk Tetra Pack',
        //   itemCategory: 'Packaged',
        //   itemUndiscountedRate: 10,
        //   isDiscountedAvailable: false,
        //   itemDiscountedRate: 10,
        //   discountAmount: 0,
        //   discountPercentage: 0,
        //   itemWeight: '100 Gms',
        //   itemImageUrl: 'https://gravatar.com/avatar/dba6bae8c566f9d4041fb9cd9ada7741?d=identicon&f=y'
        // },
        // {
        //   itemId: 'MILK1',
        //   itemName: 'Jersey Milk',
        //   itemBrand: 'Jersey',
        //   itemDescription: 'Packaged Milk Tetra Pack',
        //   itemCategory: 'Packaged',
        //   itemUndiscountedRate: 10,
        //   isDiscountedAvailable: false,
        //   itemDiscountedRate: 10,
        //   discountAmount: 0,
        //   discountPercentage: 0,
        //   itemWeight: '100 Gms',
        //   itemImageUrl: 'https://gravatar.com/avatar/dba6bae8c566f9d4041fb9cd9ada7741?d=identicon&f=y'
        // },
        // {
        //   itemId: 'MILK1',
        //   itemName: 'Jersey Milk',
        //   itemBrand: 'Jersey',
        //   itemDescription: 'Packaged Milk Tetra Pack',
        //   itemCategory: 'Packaged',
        //   itemUndiscountedRate: 10,
        //   isDiscountedAvailable: false,
        //   itemDiscountedRate: 10,
        //   discountAmount: 0,
        //   discountPercentage: 0,
        //   itemWeight: '100 Gms',
        //   itemImageUrl: 'https://gravatar.com/avatar/dba6bae8c566f9d4041fb9cd9ada7741?d=identicon&f=y'
        // },
        // {
        //   itemId: 'MILK1',
        //   itemName: 'Jersey Milk',
        //   itemBrand: 'Jersey',
        //   itemDescription: 'Packaged Milk Tetra Pack',
        //   itemCategory: 'Packaged',
        //   itemUndiscountedRate: 10,
        //   isDiscountedAvailable: false,
        //   itemDiscountedRate: 10,
        //   discountAmount: 0,
        //   discountPercentage: 0,
        //   itemWeight: '100 Gms',
        //   itemImageUrl: 'https://gravatar.com/avatar/dba6bae8c566f9d4041fb9cd9ada7741?d=identicon&f=y'
        // },
        // {
        //   itemId: 'MILK1',
        //   itemName: 'Jersey Milk',
        //   itemBrand: 'Jersey',
        //   itemDescription: 'Packaged Milk Tetra Pack',
        //   itemCategory: 'Packaged',
        //   itemUndiscountedRate: 10,
        //   isDiscountedAvailable: false,
        //   itemDiscountedRate: 10,
        //   discountAmount: 0,
        //   discountPercentage: 0,
        //   itemWeight: '100 Gms',
        //   itemImageUrl: 'https://gravatar.com/avatar/dba6bae8c566f9d4041fb9cd9ada7741?d=identicon&f=y'
        // },
        // {
        //   itemId: 'MILK1',
        //   itemName: 'Jersey Milk',
        //   itemBrand: 'Jersey',
        //   itemDescription: 'Packaged Milk Tetra Pack',
        //   itemCategory: 'Packaged',
        //   itemUndiscountedRate: 10,
        //   isDiscountedAvailable: false,
        //   itemDiscountedRate: 10,
        //   discountAmount: 0,
        //   discountPercentage: 0,
        //   itemWeight: '100 Gms',
        //   itemImageUrl: 'https://gravatar.com/avatar/dba6bae8c566f9d4041fb9cd9ada7741?d=identicon&f=y'
        // },
        // {
        //   itemId: 'MILK1',
        //   itemWeight: '100 Gms',
        //   itemName: 'Jersey Milk',
        //   itemBrand: 'Jersey',
        //   itemDescription: 'Packaged Milk Tetra Pack',
        //   itemCategory: 'Packaged',
        //   itemUndiscountedRate: 10,
        //   isDiscountedAvailable: false,
        //   itemDiscountedRate: 10,
        //   discountAmount: 0,
        //   discountPercentage: 0,
        //   itemImageUrl: 'https://gravatar.com/avatar/dba6bae8c566f9d4041fb9cd9ada7741?d=identicon&f=y'
        // },
        // {
        //   itemId: 'MILK1',
        //   itemName: 'Jersey Milk',
        //   itemBrand: 'Jersey',
        //   itemWeight: '100 Gms',
        //   itemDescription: 'Packaged Milk Tetra Pack',
        //   itemCategory: 'Packaged',
        //   itemUndiscountedRate: 10,
        //   isDiscountedAvailable: false,
        //   itemDiscountedRate: 10,
        //   discountAmount: 0,
        //   discountPercentage: 0,
        //   itemImageUrl: 'https://gravatar.com/avatar/dba6bae8c566f9d4041fb9cd9ada7741?d=identicon&f=y'
        // },
        // {
        //   itemId: 'MILK1',
        //   itemName: 'Jersey Milk',
        //   itemBrand: 'Jersey',
        //   itemDescription: 'Packaged Milk Tetra Pack',
        //   itemCategory: 'Packaged',
        //   itemUndiscountedRate: 10,
        //   isDiscountedAvailable: false,
        //   itemDiscountedRate: 10,
        //   discountAmount: 0,
        //   discountPercentage: 0,
        //   itemWeight: '100 Gms',
        //   itemImageUrl: 'https://gravatar.com/avatar/dba6bae8c566f9d4041fb9cd9ada7741?d=identicon&f=y'
        // },
        // {
        //   itemId: 'MILK1',
        //   itemName: 'Jersey Milk',
        //   itemBrand: 'Jersey',
        //   itemDescription: 'Packaged Milk Tetra Pack',
        //   itemCategory: 'Packaged',
        //   itemUndiscountedRate: 10,
        //   isDiscountedAvailable: false,
        //   itemDiscountedRate: 10,
        //   discountAmount: 0,
        //   discountPercentage: 0,
        //   itemWeight: '100 Gms',
        //   itemImageUrl: 'https://gravatar.com/avatar/dba6bae8c566f9d4041fb9cd9ada7741?d=identicon&f=y'
        // },
        // {
        //   itemId: 'MILK1',
        //   itemName: 'Jersey Milk',
        //   itemBrand: 'Jersey',
        //   itemWeight: '100 Gms',
        //   itemDescription: 'Packaged Milk Tetra Pack',
        //   itemCategory: 'Packaged',
        //   itemUndiscountedRate: 10,
        //   isDiscountedAvailable: false,
        //   itemDiscountedRate: 10,
        //   discountAmount: 0,
        //   discountPercentage: 0,
        //   itemImageUrl: 'https://gravatar.com/avatar/dba6bae8c566f9d4041fb9cd9ada7741?d=identicon&f=y'
        // },
        // {
        //   itemId: 'MILK1',
        //   itemName: 'Jersey Milk',
        //   itemBrand: 'Jersey',
        //   itemWeight: '100 Gms',
        //   itemDescription: 'Packaged Milk Tetra Pack',
        //   itemCategory: 'Packaged',
        //   itemUndiscountedRate: 10,
        //   isDiscountedAvailable: false,
        //   itemDiscountedRate: 10,
        //   discountAmount: 0,
        //   discountPercentage: 0,
        //   itemImageUrl: 'https://gravatar.com/avatar/dba6bae8c566f9d4041fb9cd9ada7741?d=identicon&f=y'
        // },
        // {
        //   itemId: 'MILK1',
        //   itemName: 'Jersey Milk',
        //   itemWeight: '100 Gms',
        //   itemBrand: 'Jersey',
        //   itemDescription: 'Packaged Milk Tetra Pack',
        //   itemCategory: 'Packaged',
        //   itemUndiscountedRate: 10,
        //   isDiscountedAvailable: false,
        //   itemDiscountedRate: 10,
        //   discountAmount: 0,
        //   discountPercentage: 0,
        //   itemImageUrl: 'https://gravatar.com/avatar/dba6bae8c566f9d4041fb9cd9ada7741?d=identicon&f=y'
        // },
        // {
        //   itemId: 'MILK1',
        //   itemName: 'Jersey Milk',
        //   itemBrand: 'Jersey',
        //   itemDescription: 'Packaged Milk Tetra Pack',
        //   itemCategory: 'Packaged',
        //   itemUndiscountedRate: 10,
        //   isDiscountedAvailable: false,
        //   itemWeight: '100 Gms',
        //   itemDiscountedRate: 10,
        //   discountAmount: 0,
        //   discountPercentage: 0,
        //   itemImageUrl: 'https://gravatar.com/avatar/dba6bae8c566f9d4041fb9cd9ada7741?d=identicon&f=y'
        // },
        // {
        //   itemId: 'MILK1',
        //   itemName: 'Jersey Milk',
        //   itemBrand: 'Jersey',
        //   itemDescription: 'Packaged Milk Tetra Pack',
        //   itemCategory: 'Packaged',
        //   itemUndiscountedRate: 10,
        //   isDiscountedAvailable: false,
        //   itemDiscountedRate: 10,
        //   itemWeight: '100 Gms',
        //   discountAmount: 0,
        //   discountPercentage: 0,
        //   itemImageUrl: 'https://gravatar.com/avatar/dba6bae8c566f9d4041fb9cd9ada7741?d=identicon&f=y'
        // },
        // {
        //   itemId: 'MILK1',
        //   itemName: 'Jersey Milk',
        //   itemBrand: 'Jersey',
        //   itemDescription: 'Packaged Milk Tetra Pack',
        //   itemCategory: 'Packaged',
        //   itemUndiscountedRate: 10,
        //   isDiscountedAvailable: false,
        //   itemWeight: '100 Gms',
        //   itemDiscountedRate: 10,
        //   discountAmount: 0,
        //   discountPercentage: 0,
        //   itemImageUrl: 'https://gravatar.com/avatar/dba6bae8c566f9d4041fb9cd9ada7741?d=identicon&f=y'
        // },
        // {
        //   itemId: 'MILK1',
        //   itemName: 'Jersey Milk',
        //   itemWeight: '100 Gms',
        //   itemBrand: 'Jersey',
        //   itemDescription: 'Packaged Milk Tetra Pack',
        //   itemCategory: 'Packaged',
        //   itemUndiscountedRate: 10,
        //   isDiscountedAvailable: false,
        //   itemDiscountedRate: 10,
        //   discountAmount: 0,
        //   discountPercentage: 0,
        //   itemImageUrl: 'https://gravatar.com/avatar/dba6bae8c566f9d4041fb9cd9ada7741?d=identicon&f=y'
        // },
        // {
        //   itemId: 'MILK1',
        //   itemName: 'Jersey Milk',
        //   itemWeight: '100 Gms',
        //   itemBrand: 'Jersey',
        //   itemDescription: 'Packaged Milk Tetra Pack',
        //   itemCategory: 'Packaged',
        //   itemUndiscountedRate: 10,
        //   isDiscountedAvailable: false,
        //   itemDiscountedRate: 10,
        //   discountAmount: 0,
        //   discountPercentage: 0,
        //   itemImageUrl: 'https://gravatar.com/avatar/dba6bae8c566f9d4041fb9cd9ada7741?d=identicon&f=y'
        // },
        // {
        //   itemId: 'MILK1',
        //   itemName: 'Jersey Milk',
        //   itemWeight: '100 Gms',
        //   itemBrand: 'Jersey',
        //   itemDescription: 'Packaged Milk Tetra Pack',
        //   itemCategory: 'Packaged',
        //   itemUndiscountedRate: 10,
        //   isDiscountedAvailable: false,
        //   itemDiscountedRate: 10,
        //   discountAmount: 0,
        //   discountPercentage: 0,
        //   itemImageUrl: 'https://gravatar.com/avatar/dba6bae8c566f9d4041fb9cd9ada7741?d=identicon&f=y'
        // },
        // {
        //   itemId: 'MILK1',
        //   itemName: 'Jersey Milk',
        //   itemWeight: '100 Gms',
        //   itemBrand: 'Jersey',
        //   itemDescription: 'Packaged Milk Tetra Pack',
        //   itemCategory: 'Packaged',
        //   itemUndiscountedRate: 10,
        //   isDiscountedAvailable: false,
        //   itemDiscountedRate: 10,
        //   discountAmount: 0,
        //   discountPercentage: 0,
        //   itemImageUrl: 'https://gravatar.com/avatar/dba6bae8c566f9d4041fb9cd9ada7741?d=identicon&f=y'
        // },
        // {
        //   itemId: 'MILK1',
        //   itemName: 'Jersey Milk',
        //   itemBrand: 'Jersey',
        //   itemDescription: 'Packaged Milk Tetra Pack',
        //   itemCategory: 'Packaged',
        //   itemUndiscountedRate: 10,
        //   isDiscountedAvailable: false,
        //   itemDiscountedRate: 10,
        //   discountAmount: 0,
        //   discountPercentage: 0,
        //   itemWeight: '100 Gms',
        //   itemImageUrl: 'https://gravatar.com/avatar/dba6bae8c566f9d4041fb9cd9ada7741?d=identicon&f=y'
        // },
        // {
        //   itemId: 'MILK1',
        //   itemName: 'Jersey Milk',
        //   itemBrand: 'Jersey',
        //   itemDescription: 'Packaged Milk Tetra Pack',
        //   itemCategory: 'Packaged',
        //   itemUndiscountedRate: 10,
        //   isDiscountedAvailable: false,
        //   itemDiscountedRate: 10,
        //   discountAmount: 0,
        //   discountPercentage: 0,
        //   itemWeight: '100 Gms',
        //   itemImageUrl: 'https://gravatar.com/avatar/dba6bae8c566f9d4041fb9cd9ada7741?d=identicon&f=y'
        // },
        // {
        //   itemId: 'MILK1',
        //   itemName: 'Jersey Milk',
        //   itemBrand: 'Jersey',
        //   itemDescription: 'Packaged Milk Tetra Pack',
        //   itemCategory: 'Packaged',
        //   itemUndiscountedRate: 10,
        //   isDiscountedAvailable: false,
        //   itemDiscountedRate: 10,
        //   discountAmount: 0,
        //   discountPercentage: 0,
        //   itemWeight: '100 Gms',
        //   itemImageUrl: 'https://gravatar.com/avatar/dba6bae8c566f9d4041fb9cd9ada7741?d=identicon&f=y'
        // },
        // {
        //   itemId: 'MILK1',
        //   itemName: 'Jersey Milk',
        //   itemBrand: 'Jersey',
        //   itemDescription: 'Packaged Milk Tetra Pack',
        //   itemCategory: 'Packaged',
        //   itemUndiscountedRate: 10,
        //   isDiscountedAvailable: false,
        //   itemDiscountedRate: 10,
        //   discountAmount: 0,
        //   discountPercentage: 0,
        //   itemWeight: '100 Gms',
        //   itemImageUrl: 'https://gravatar.com/avatar/dba6bae8c566f9d4041fb9cd9ada7741?d=identicon&f=y'
        // },
        // {
        //   itemId: 'MILK1',
        //   itemName: 'Jersey Milk',
        //   itemBrand: 'Jersey',
        //   itemDescription: 'Packaged Milk Tetra Pack',
        //   itemCategory: 'Packaged',
        //   itemUndiscountedRate: 10,
        //   isDiscountedAvailable: false,
        //   itemDiscountedRate: 10,
        //   discountAmount: 0,
        //   discountPercentage: 0,
        //   itemWeight: '100 Gms',
        //   itemImageUrl: 'https://gravatar.com/avatar/dba6bae8c566f9d4041fb9cd9ada7741?d=identicon&f=y'
        // },
        // {
        //   itemId: 'MILK1',
        //   itemName: 'Jersey Milk',
        //   itemBrand: 'Jersey',
        //   itemDescription: 'Packaged Milk Tetra Pack',
        //   itemCategory: 'Packaged',
        //   itemUndiscountedRate: 10,
        //   isDiscountedAvailable: false,
        //   itemDiscountedRate: 10,
        //   discountAmount: 0,
        //   discountPercentage: 0,
        //   itemWeight: '100 Gms',
        //   itemImageUrl: 'https://gravatar.com/avatar/dba6bae8c566f9d4041fb9cd9ada7741?d=identicon&f=y'
        // },
        // {
        //   itemId: 'MILK1',
        //   itemName: 'Jersey Milk',
        //   itemBrand: 'Jersey',
        //   itemDescription: 'Packaged Milk Tetra Pack',
        //   itemCategory: 'Packaged',
        //   itemUndiscountedRate: 10,
        //   isDiscountedAvailable: false,
        //   itemDiscountedRate: 10,
        //   discountAmount: 0,
        //   itemWeight: '100 Gms',
        //   discountPercentage: 0,
        //   itemImageUrl: 'https://gravatar.com/avatar/dba6bae8c566f9d4041fb9cd9ada7741?d=identicon&f=y'
        // },
        // {
        //   itemId: 'MILK1',
        //   itemName: 'Jersey Milk',
        //   itemBrand: 'Jersey',
        //   itemDescription: 'Packaged Milk Tetra Pack',
        //   itemCategory: 'Packaged',
        //   itemUndiscountedRate: 10,
        //   isDiscountedAvailable: false,
        //   itemDiscountedRate: 10,
        //   itemWeight: '100 Gms',
        //   discountAmount: 0,
        //   discountPercentage: 0,
        //   itemImageUrl: 'https://gravatar.com/avatar/dba6bae8c566f9d4041fb9cd9ada7741?d=identicon&f=y'
        // },
        // {
        //   itemId: 'MILK1',
        //   itemName: 'Jersey Milk',
        //   itemBrand: 'Jersey',
        //   itemDescription: 'Packaged Milk Tetra Pack',
        //   itemCategory: 'Packaged',
        //   itemUndiscountedRate: 10,
        //   itemWeight: '100 Gms',
        //   isDiscountedAvailable: false,
        //   itemDiscountedRate: 10,
        //   discountAmount: 0,
        //   discountPercentage: 0,
        //   itemImageUrl: 'https://gravatar.com/avatar/dba6bae8c566f9d4041fb9cd9ada7741?d=identicon&f=y'
        // },
        // {
        //   itemId: 'MILK1',
        //   itemName: 'Jersey Milk',
        //   itemBrand: 'Jersey',
        //   itemWeight: '100 Gms',
        //   itemDescription: 'Packaged Milk Tetra Pack',
        //   itemCategory: 'Packaged',
        //   itemUndiscountedRate: 10,
        //   isDiscountedAvailable: false,
        //   itemDiscountedRate: 10,
        //   discountAmount: 0,
        //   discountPercentage: 0,
        //   itemImageUrl: 'https://gravatar.com/avatar/dba6bae8c566f9d4041fb9cd9ada7741?d=identicon&f=y'
        // },
        // {
        //   itemId: 'MILK1',
        //   itemName: 'Jersey Milk',
        //   itemBrand: 'Jersey',
        //   itemDescription: 'Packaged Milk Tetra Pack',
        //   itemCategory: 'Packaged',
        //   itemUndiscountedRate: 10,
        //   isDiscountedAvailable: false,
        //   itemWeight: '100 Gms',
        //   itemDiscountedRate: 10,
        //   discountAmount: 0,
        //   discountPercentage: 0,
        //   itemImageUrl: 'https://gravatar.com/avatar/dba6bae8c566f9d4041fb9cd9ada7741?d=identicon&f=y'
        // },
        // {
        //   itemId: 'MILK1',
        //   itemName: 'Jersey Milk',
        //   itemBrand: 'Jersey',
        //   itemDescription: 'Packaged Milk Tetra Pack',
        //   itemCategory: 'Packaged',
        //   itemUndiscountedRate: 10,
        //   itemWeight: '100 Gms',
        //   isDiscountedAvailable: false,
        //   itemDiscountedRate: 10,
        //   discountAmount: 0,
        //   discountPercentage: 0,
        //   itemImageUrl: 'https://gravatar.com/avatar/dba6bae8c566f9d4041fb9cd9ada7741?d=identicon&f=y'
        // },
        // {
        //   itemId: 'MILK1',
        //   itemName: 'Jersey Milk',
        //   itemBrand: 'Jersey',
        //   itemDescription: 'Packaged Milk Tetra Pack',
        //   itemCategory: 'Packaged',
        //   itemUndiscountedRate: 10,
        //   isDiscountedAvailable: false,
        //   itemWeight: '100 Gms',
        //   itemDiscountedRate: 10,
        //   discountAmount: 0,
        //   discountPercentage: 0,
        //   itemImageUrl: 'https://gravatar.com/avatar/dba6bae8c566f9d4041fb9cd9ada7741?d=identicon&f=y'
        // },
        // {
        //   itemId: 'MILK1',
        //   itemName: 'Jersey Milk',
        //   itemBrand: 'Jersey',
        //   itemDescription: 'Packaged Milk Tetra Pack',
        //   itemWeight: '100 Gms',
        //   itemCategory: 'Packaged',
        //   itemUndiscountedRate: 10,
        //   isDiscountedAvailable: false,
        //   itemDiscountedRate: 10,
        //   discountAmount: 0,
        //   discountPercentage: 0,
        //   itemImageUrl: 'https://gravatar.com/avatar/dba6bae8c566f9d4041fb9cd9ada7741?d=identicon&f=y'
        // },
        // {
        //   itemId: 'MILK1',
        //   itemName: 'Jersey Milk',
        //   itemBrand: 'Jersey',
        //   itemDescription: 'Packaged Milk Tetra Pack',
        //   itemCategory: 'Packaged',
        //   itemUndiscountedRate: 10,
        //   isDiscountedAvailable: false,
        //   itemDiscountedRate: 10,
        //   discountAmount: 0,
        //   itemWeight: '100 Gms',
        //   discountPercentage: 0,
        //   itemImageUrl: 'https://gravatar.com/avatar/dba6bae8c566f9d4041fb9cd9ada7741?d=identicon&f=y'
        // },
        // {
        //   itemId: 'MILK1',
        //   itemName: 'Jersey Milk',
        //   itemBrand: 'Jersey',
        //   itemDescription: 'Packaged Milk Tetra Pack',
        //   itemCategory: 'Packaged',
        //   itemUndiscountedRate: 10,
        //   isDiscountedAvailable: false,
        //   itemDiscountedRate: 10,
        //   itemWeight: '100 Gms',
        //   discountAmount: 0,
        //   discountPercentage: 0,
        //   itemImageUrl: 'https://gravatar.com/avatar/dba6bae8c566f9d4041fb9cd9ada7741?d=identicon&f=y'
        // },
        // {
        //   itemId: 'MILK1',
        //   itemName: 'Jersey Milk',
        //   itemBrand: 'Jersey',
        //   itemWeight: '100 Gms',
        //   itemDescription: 'Packaged Milk Tetra Pack',
        //   itemCategory: 'Packaged',
        //   itemUndiscountedRate: 10,
        //   isDiscountedAvailable: false,
        //   itemDiscountedRate: 10,
        //   discountAmount: 0,
        //   discountPercentage: 0,
        //   itemImageUrl: 'https://gravatar.com/avatar/dba6bae8c566f9d4041fb9cd9ada7741?d=identicon&f=y'
        // },
        // {
        //   itemId: 'MILK1',
        //   itemName: 'Jersey Milk',
        //   itemBrand: 'Jersey',
        //   itemDescription: 'Packaged Milk Tetra Pack',
        //   itemCategory: 'Packaged',
        //   itemUndiscountedRate: 10,
        //   isDiscountedAvailable: false,
        //   itemWeight: '100 Gms',
        //   itemDiscountedRate: 10,
        //   discountAmount: 0,
        //   discountPercentage: 0,
        //   itemImageUrl: 'https://gravatar.com/avatar/dba6bae8c566f9d4041fb9cd9ada7741?d=identicon&f=y'
        // },
        // {
        //   itemId: 'MILK1',
        //   itemName: 'Jersey Milk',
        //   itemBrand: 'Jersey',
        //   itemWeight: '100 Gms',
        //   itemDescription: 'Packaged Milk Tetra Pack',
        //   itemCategory: 'Packaged',
        //   itemUndiscountedRate: 10,
        //   isDiscountedAvailable: false,
        //   itemDiscountedRate: 10,
        //   discountAmount: 0,
        //   discountPercentage: 0,
        //   itemImageUrl: 'https://gravatar.com/avatar/dba6bae8c566f9d4041fb9cd9ada7741?d=identicon&f=y'
        // },
        // {
        //   itemId: 'MILK1',
        //   itemName: 'Jersey Milk',
        //   itemBrand: 'Jersey',
        //   itemDescription: 'Packaged Milk Tetra Pack',
        //   itemCategory: 'Packaged',
        //   itemUndiscountedRate: 10,
        //   isDiscountedAvailable: false,
        //   itemWeight: '100 Gms',
        //   itemDiscountedRate: 10,
        //   discountAmount: 0,
        //   discountPercentage: 0,
        //   itemImageUrl: 'https://gravatar.com/avatar/dba6bae8c566f9d4041fb9cd9ada7741?d=identicon&f=y'
        // },
        // {
        //   itemId: 'MILK1',
        //   itemName: 'Jersey Milk',
        //   itemBrand: 'Jersey',
        //   itemDescription: 'Packaged Milk Tetra Pack',
        //   itemCategory: 'Packaged',
        //   itemUndiscountedRate: 10,
        //   itemWeight: '100 Gms',
        //   isDiscountedAvailable: false,
        //   itemDiscountedRate: 10,
        //   discountAmount: 0,
        //   discountPercentage: 0,
        //   itemImageUrl: 'https://gravatar.com/avatar/dba6bae8c566f9d4041fb9cd9ada7741?d=identicon&f=y'
        // }
      ]
    },
    {
      shopId: "NALLAGANDALASHOP1",
      shopName: 'Regent Park General Store',
      shopType: "GROCERY",
      shopLocation: "REGENT PARK APARTMENT",
      shopAddress: "REGENT PARK APARTMENT",
      shopPostalCode: 500019,
      shopImageUrl: 'https://gravatar.com/avatar/dba6bae8c566f9d4041fb9cd9ada7741?d=identicon&f=y',
      shopRating: 4.5,
      shopOfferedItemsList : [
        {
          itemId: 'MILK1',
          itemName: 'Mother Dairy Milk',
          itemBrand: 'Mother Dairy',
          itemDescription: 'Packaged Milk Tetra Pack',
          itemCategory: 'Packaged',
          itemUndiscountedRate: 10,
          itemWeight: 100,
          itemUnit: 'g',
          isDiscountedAvailable: false,
          itemDiscountedRate: 10,
          discountAmount: 0,
          discountPercentage: 0,
          itemCount: 0,
          itemImageUrl: 'https://gravatar.com/avatar/dba6bae8c566f9d4041fb9cd9ada7741?d=identicon&f=y'
        }
      ]
    }
  ];

  constructor() { }

  getAllShopList() {
    // return [...this.shopList];
    return [...this.shopList];
  }

  getShopOfferedItems(shopId: string) {
    // return {
    //   ...this.shopList.find(shop => shop.shopId === shopId)
    // };
    return this.shopList.find(shop => shop.shopId === shopId);
  }
}
